name: CreatureCapture
main: me.crylonz.CreatureCapture
version: "2.2.1"
author: Crylonz
description: Capture monster !
api-version: "1.13"
commands:
  cc:
    description: is the base command for CreatureCapture plugin.
    usage: /cc <get|reload>
    #permission: creaturecapture.cc

permissions:
  creaturecapture.capture:
    description: Allows you to capture creature
    default: op
  creaturecapture.cc:
    description: Allows you to use creature capture commands
    default: op
  creaturecapture.get:
    description: Allows you to give you capture bow
    default: op
  creaturecapture.reload:
    description: Allows you to reload settings.
    default: op