name: CreatureCapture
main: me.crylonz.CreatureCapture
version: "1.12"
author: Crylonz
description: Capture monster !
api-version: "1.13"
commands:
  cc:
    description: give you the capture bow
    usage: /cc
    permission: creaturecapture.cc

permissions:
  creaturecapture.capture:
    description: Allows you to capture creature
    default: op
  creaturecapture.cc:
    description: Allows you to give you capture bow
    default: op